#!/usr/bin/env bash

word_file=$(mktemp /tmp/new_word.XXXX)
epoch=$(date '+%s')
tomorrow=$(($epoch + 86400))

cat << EOF > $word_file
----------------------------------------
id: $epoch
foreign:
english:
notes:
EOF

vim $word_file -c "normal jj$"

if ! egrep -q 'english: ?\w' $word_file
then
    echo "Aborting due to badly formatted english" && exit 1
fi

if ! egrep -q 'foreign: ?\w' $word_file
then
    echo "Aborting due to badly formatted foreign" && exit 1
fi


cat $word_file >> words
rm $word_file
cat << EOF >> due_dates
$epoch $tomorrow
EOF
